// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/academias" | "/adimin" | "/admin" | "/chat" | "/configuracoes" | "/dashboard" | "/eventos" | "/eventos/[id]" | "/login" | "/loja" | "/notificacoes" | "/pagamento" | "/pagamento/falha" | "/pagamento/pendente" | "/pagamento/sucesso" | "/planos" | "/planos/academia" | "/profile" | "/ranking" | "/register" | "/tecnicos" | "/tecnicos/[atletaId]" | "/treino"
type AppRouteHandlerRoutes = "/api/ranking/users"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/academias": {}
  "/adimin": {}
  "/admin": {}
  "/api/ranking/users": {}
  "/chat": {}
  "/configuracoes": {}
  "/dashboard": {}
  "/eventos": {}
  "/eventos/[id]": { "id": string; }
  "/login": {}
  "/loja": {}
  "/notificacoes": {}
  "/pagamento": {}
  "/pagamento/falha": {}
  "/pagamento/pendente": {}
  "/pagamento/sucesso": {}
  "/planos": {}
  "/planos/academia": {}
  "/profile": {}
  "/ranking": {}
  "/register": {}
  "/tecnicos": {}
  "/tecnicos/[atletaId]": { "atletaId": string; }
  "/treino": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
